### ISSUE TITLE
ServiceKey Issue

### ISSUE THREAD

**Issue by amorfati0310** [airkorea/howto#10]
서비스 키를 재 발급 받아도 계속 api 호출하면 아래와 같은 결과가 나옵니다 
지인 분 ServiceKey로 하면 제대로 결과가 나와요 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>
    <header>
        <resultCode>20</resultCode>
        <resultMsg>SERVICE ACCESS DENIED ERROR.</resultMsg>
    </header>
</response>
```

**Comment by airkoreadev** [comment]
안녕하세요. 한국환경공단 OpenAPI 관리자입니다.말씀하신 20번 에러는 활용신청하지 않은 API를 호출하실 때 발생하는 에러입니다.에어코리아 서비스는 서비스 마다, 오퍼레이션을 선택하셔서 신청하셔야합니다. 예를 들어, 대기오염정보조회 서비스만 신청하셨다면 측정소정보 조회서비스는 사용하시지 못합니다.신청하신 서비스 확인하신 후 사용 부탁드립니다.감사합니다 :D


	---------- 원본 메일 ----------
	보낸사람: "Chany" <notifications@github.com>
	받는사람: "airkorea/howto" <howto@noreply.github.com>

	참조: "Subscribed" <subscribed@noreply.github.com>

	날짜: 2020-03-26 (목) 04:00:40
	제목: [airkorea/howto] ServiceKey Issue (#10)
	
	
서비스 키를 재 발급 받아도 계속 api 호출하면 아래와 같은 결과가 나옵니다
지인 분 ServiceKey로 하면 제대로 결과가 나와요
<?xml version="1.0" encoding="UTF-8"?>
<response>
    <header>
        <resultCode>20</resultCode>
        <resultMsg>SERVICE ACCESS DENIED ERROR.</resultMsg>
    </header>
</response>

**Comment by amorfati0310** [comment]
@airkoreadev  감사합니다 endpoint 별로 요청을 해야 되는 지 몰랐네요 문서에 여러개가 같이 있어서 ㅜ
